config/routes.rb
Rails.application.routes.draw do

  resources :stores 
  root "wines#index"
  get "wines/" => "wines#index"

  get "wines/new" => "wines#new", as: :new_wine

  get "wines/:id" => "wines#show", as: :wine

  post "wines/" => "wines#create"

  get "wines/:id/edit" => "wines#edit", as: :edit_wine

  patch "wines/:id" => "wines#update"

  delete "wines/:id" => "wines#destroy" 

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wineshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_footer.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br><br>
<br>
<br>
<br>
<br>
<br>

<footer><p>&copy; 2015 Ian Poston | <a href="http://www.ianposton.com">Home</a></p></footer>

app/views/stores/index.html.erb
<div class="pure-menu pure-menu-open pure-menu-horizontal">
		<ul>
			<li><%= link_to "Add A New Wine", new_wine_path %></li>
			<li><%= link_to "Add more wine stores!", new_store_path %></li>
		</ul>
</div>

<h1>All our stores</h1>

<ul>
	
	<% @stores.each do |store| %>
	<h3><li><%= store.name %></li></h3>

	<% end %>
	
</ul>

app/views/stores/new.html.erb
<div class="pure-menu pure-menu-open pure-menu-horizontal">
  <ul>
       
       <li><%= link_to "Back to the list of wine stores", stores_path %></li>
       <li><%= link_to "Back to the list of wines", wines_path %></li>
</ul>
</div>



<h1>New Store</h1>

<%= form_for @store do |f| %>

<div class="container">
	
	
	
	  <div class="form-group">
	    <%= f.label :Name %><br>
	    <%= f.text_field :name, class: 'form-control' %>
	  </div>
	 <div class="actions">
	    <%= f.submit 'Add New Store!', class: 'btn btn-warning' %>
</div>

</div>

<% end %>

app/views/wines/index.html.erb
<div class="pure-menu pure-menu-open pure-menu-horizontal">
		<ul>
			<li><%= link_to "Add A New Wine", new_wine_path %></li>
		</ul>
</div>

<h1>Choice Wines</h1>
	

<ol>

	<% @wines.each do |wine| %>

	<h3><li> <%= wine.name %> | <%= wine.grape %> | <button class="pure-menu pure-button"><%= link_to "More info", wine_path(wine) %></button></li></h3>

	<% end %>

</ol>

app/views/wines/new.html.erb
<div class="pure-menu pure-menu-open pure-menu-horizontal">
		<ul>
			<li><%= link_to "Add A New Wine", new_wine_path %></li>
			<li><%= link_to "Add more wine stores", new_store_path %></li>
			<li><%= link_to "Back to list", wines_path %></li>
		</ul>
</div>

<div class="container">
	<h1>Add a New Wine!</h1>

    
	 <%= form_for @wine, html: { multipart: true } do |f| %>
	  <% if @wine.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

	      <ul>
		      <% @wine.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div class="form-group">
	    <%= f.label :Name %><br>
	    <%= f.text_field :name, class: 'form-control' %>
	  </div>
	  <div class="form-group">
	    <%= f.label :Grape %><br>
	    <%= f.text_field :grape, class: 'form-control' %>
	  </div>
	  	<div class="form-group">
	    <%= f.label :Region %><br>
	    <%= f.text_field :region, class: 'form-control' %>
	  </div>
	  <div class="form-group">
	    <%= f.label :Year %><br>
	    <%= f.text_field :year, class: 'form-control' %>
	  </div>
	  <div class="form-group">
	   		<p><%= f.label :Store %><%= f.collection_select :store, Store.all, :id, :name  %></p>
	   </div>
	  <div class="actions">
	    <%= f.submit 'Add New Wine!', class: 'btn btn-warning' %>
	  </div>
	<% end %>

</div> <!-- end container -->

app/views/wines/show.html.erb
<div class="pure-menu pure-menu-open pure-menu-horizontal">
<ul>
<li><%= link_to "Edit this wine!", edit_wine_path(@wine) %></li>

<li><%= link_to "Delete this wine!", :wine, method: :delete, data: { confirm: "Are you sure you want to delete this wine?"} %></li>

<li><%= link_to "Back to the list!", wines_path %></li>
</ul>
</div>

<h1> <%= @wine.name %> </h1>

  <h3>This is a <%= @wine.grape %> from <%= @wine.region %> and it was produced in <%= @wine.year %></h3> 

  <% if @wine.store %>

    <h3>It is sold by <%= @wine.store.name %>.</h3>

<% end %>